config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  get '/practices' => "editors#index", as: 'practices'
  resources :editors do
    collection do
      post :evaluate
      post :spec
      get :realtime
      post :set_realtime
      post :toggle_observer
    end
  end

  post '/sessions' => 'sessions#create'
  get '/sign_out' => 'sessions#destroy'

end

app/models/code.rb
class Code < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  def admin?
    admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from Exception, with: :error_message
  helper_method :current_user

  def error_message(e)
    render json: {
      result: "#{e.class}: #{e.message}"
    }
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user])
  end
end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController
  before_action :authenticate

  def index
    @q    = params[:q].to_i || 0
    CurrentCode.set_q(@q)
    @code = Code.find_by_q(@q)
  end

  def evaluate
    parse_code
    result = eval(@code_string)
    render :json => {:result => result}
  end

  def spec
    parse_code
    num = params[:q].to_i || 0
    path = "#{Rails.root}/lib/code/#{num}.rb"
    File.open(path, "w+") {|file| file.write(@code_string) }
    if code_valid?
      eval(File.read(path))
      result = %x[cd #{Rails.root} && rspec spec/lib/#{num}_spec.rb --format html]
    else
      result = '錯誤'
    end
    render json: {
      result: result,
      status: 'ok'
    }
  end

  def realtime
    if !current_user.admin? && !CurrentCode.observer
      @observer = 'non-observer'
    end
    render json: {
      code:   CurrentCode.code.join("\n"),
      result: CurrentCode.result,
      observer: @observer,
      q: CurrentCode.q
    }
  end

  def set_realtime
    CurrentCode.set_code(params[:code])     if params[:code]
    CurrentCode.set_result(params[:result]) if params[:result]
    result = 'ok'
    if !current_user.admin? && CurrentCode.observer
      result = 'observer'
    end
    render json: {
      result: result
    }
  end

  def toggle_observer
    CurrentCode.set_observer(CurrentCode.observer.!)
    render json: {
      result: 'ok'
    }
  end

  private

  def parse_code
    code_array = params[:code]
    if code_array.class == Array && code_array.length > 0
      @code_string = code_array.inject("") { |result, line| result += line + ";"}
    end
  end

  def authenticate
    redirect_to '/' unless current_user
  end

  def code_valid?
    ['File', 'FileUtils', 'rm -rf', 'system(', 'system ', '%x['].any? {|str| @code_string.include?(str) }.!
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to '/practices' if current_user
  end

  def create
    @user = User.find_by_account(params[:account])
    p @user
    if @user && password_match
      session[:user] = @user.id 
    else
      flash[:notice] = '帳號或密碼錯誤'
    end
    redirect_to '/practices'
  end

  def password_match
    require 'digest'
    @user.password == Digest::SHA256.hexdigest(params[:password])
  end

  def destroy
    session[:user] = nil
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/views/editors/index.html.erb
<div class="wrapper">
  <div class="header" style="margin-top:15px;"><span>實作 <%= @code.q %></span></div>
  <div id="question"><%= @code.description %></div>
  <div class="header mode"><span>寫作模式</span></div>
  <div id="editor"><%= @code.content %></div>
  <div id="result">
    <div id="body"></div>
  </div>
  <button class="send btn btn-primary pull-right" id="send">送出</button>
  <% if current_user.admin? %>
    <button class="btn btn-success pull-right" id="observer" style="">切換模式</button>
    <%= link_to '下一題', practices_path(q: @q + 1), class: 'btn btn-default pull-right', id: 'next' %>
    <%= link_to('上一題', practices_path(q: @q - 1), class: 'btn btn-default pull-right', id: 'previous') unless @q == 0 %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>編輯器</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= notice %>
<%= link_to('登出', '/sign_out', class: 'pull-right', style: 'margin-top: 5px; margin-right: 40px;') if current_user %>
<%= yield %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</body>
</html>